# Generated by Django 5.1.4 on 2024-12-12 18:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='table_name',
            field=models.CharField(default=api.models.unique_table_name, max_length=30),
        ),
    ]
